#!/bin/bash

export STARPU_MPI_STATS=1

# Define an array of matrix sizes
matrix_sizes=(5000 25000 50000 75000 100000 125000)
num_procs=15
tile_size=500
r=6

for size in "${matrix_sizes[@]}"; do
    echo "Running with matrix size: $size"

    sbc_file="sbc_$size.txt"
    echo "python sbc.py -r "$r" -n "$size" -o "$sbc_file""

    python3 /scratch/ama10047/sbc.py -r "$r" -n "$size" -o "$sbc_file" --extended

    log_file="test_$size.log"
    data_file="data_$size.txt"

    # Generate SBATCH script
    sbatch_script="job_$size.sbatch"

    cat > "$sbatch_script" <<EOF
#!/bin/bash
#SBATCH --nodes=15
#SBATCH --tasks-per-node=1
#SBATCH --cpus-per-task=12
#SBATCH --mem=100GB
#SBATCH --output=output_$size.txt

module load chameleon

srun chameleon_dtesting -o potrf -n "$size" -b 500 --custom="$sbc_file" --nowarmup --mtxfmt=1 2>&1 | tee "$log_file"

EOF

    # Submit job to the queue
    sbatch "$sbatch_script"

    echo "Submitted job for matrix size: $size"
done
